apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
spec:
  selector:
    matchLabels:
      app: weatherapp
  replicas: 4
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: weatherapp
	imagePullPolicy: Never
        ports:
        - containerPort: 8080
